# Run tests against supported Node versions

version: 2.1

orbs:
  win: circleci/windows@5.0.0
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.3.0

executors:
  node18:
    docker:
      - image: cimg/node:18.0.0-browsers
    working_directory: ~/workspace
  node16:
    docker:
      # Oldest version supported by the jasmine package
      - image: cimg/node:16.14.0-browsers
    working_directory: ~/workspace

jobs:
  test:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - run:
          name: Report Node and NPM versions
          command: echo "Using Node $(node --version) and NPM $(npm --version)"
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Clean up after Chromedriver installation
          command: |
            # browser-tools/install-chromedriver drops a LICENSE.chromedriver
            # file in the project root dir. That causes the spec in
            # spec/npmPackageSpec.js that checks which files we're packaging
            # to fail, since `npm pack` includes LICENSE.* files even if they
            # aren't allowlisted. We don't distribute ChromeDriver, so we don't
            # need to package its license file.
            rm LICENSE.chromedriver
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Report core version
          command: echo 'console.log(require("jasmine-core").version())' | node
      - run:
          name: Run tests
          command: npm test
      - persist_to_workspace:
          root: .
          paths:
            - .

  test_win:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: nvm install 16.14.0 && nvm use 16.14.0
      - run:
          name: Report Node and NPM versions
          command: echo "Using Node $(node --version) and NPM $(npm --version)"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Report core version
          command: echo 'console.log(require("jasmine-core").version())' | node
      - run:
          name: Run tests
          command: JASMINE_NO_BROWSER_TESTS=y npm test

  saucelabs_integration_test:
    executor: node16
    steps:
    - attach_workspace:
        at: .
    - browser-tools/install-chrome
    - browser-tools/install-chromedriver
    - run:
        name: Clean up after Chromedriver installation
        command: |
          # browser-tools/install-chromedriver drops a LICENSE.chromedriver
          # file in the project root dir. That causes the spec in
          # spec/npmPackageSpec.js that checks which files we're packaging
          # to fail, since `npm pack` includes LICENSE.* files even if they
          # aren't allowlisted. We don't distribute ChromeDriver, so we don't
          # need to package its license file.
          rm LICENSE.chromedriver
    - run:
        name: Install Sauce Connect
        command: |
          cd /tmp
          curl https://saucelabs.com/downloads/sc-4.8.2-linux.tar.gz | tar zxf -
          chmod +x sc-4.8.2-linux/bin/sc
          mkdir ~/bin
          cp sc-4.8.2-linux/bin/sc ~/bin
          ~/bin/sc --version
    - run:
        name: Run tests
        command: |
          export PATH=$PATH:$HOME/workspace/bin
          export USE_SAUCE=true
          scripts/start-sauce-connect sauce-pidfile
          set +o errexit
          npm test
          exitcode=$?
          set -o errexit
          scripts/stop-sauce-connect $(cat sauce-pidfile)
          exit $exitcode

workflows:
  version: 2
  push: &push_workflow
    jobs:
      - test:
          matrix:
            parameters:
                executor: ["node18", "node16"]
      - test_win
      - saucelabs_integration_test:
          requires:
            - "test-node16"
          filters:
            branches:
              ignore: /pull\/.*/ # Don't run on pull requests.

  cron:
    <<: *push_workflow
    triggers:
      - schedule:
          # Times are UTC.
          cron: "0 9 * * *"
          filters:
            branches:
               only:
                 - main
